### ISSUE TITLE
Action is broken

### ISSUE THREAD

**Issue by ckotzbauer** [philips-labs/slsa-provenance-action#135]
Hi,
I try to update my action to 0.6.0, but it fails always with strange errors:

Workflow:
```yaml
    - name: Generate provenance
      uses: philips-labs/slsa-provenance-action@8f3f6a835ccfa2c0d5fb1d6dce15691a86575659
      with:
        arguments: -d --artifact-path ${{ inputs.artifact-path }} --extra-materials material.json --output-path ${{ inputs.output }}
```

Debug-Logs:

```
docker run image=ghcr.io/philips-labs/slsa-provenance:v0.6.0 platform= entrypoint=[] cmd=["generate" "files" "--github-context" "<redacted>" "--runner-context" "<redacted>" "-d" "--artifact-path" "dist/" "--extra-materials" "material.json" "--output-path" "provenance.json"]
Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "generate": executable file not found in $PATH: unknown
```

This seems to be an error of the action itself, I really don't know what could be wrong to my config regarding to the docs.
Does anybody have a tip for me?

Thanks!
