### ISSUE TITLE
entryPoint in report is incorrect

### ISSUE THREAD

**Issue by JeroenKnoops** [philips-labs/slsa-provenance-action#226]
When a SLSA-provenance file is created, the entryPoint seems to be incorrect.

## Example

See https://rekor.tlog.dev/?logIndex=7361109 for an example of an incorrect entryPoint.

```
predicate:
  builder:
    id: >-
      https://github.com/philips-software/docker-node/Attestations/GitHubHostedActions@v1
  buildType: https://github.com/Attestations/GitHubActionsWorkflow@v1
  invocation:
    configSource:
      uri: git+https://github.com/philips-software/docker-node
      digest:
        sha1: 39fc5e37b2210294172650a7ea37e63134c69005
      entryPoint: Build Docker image
```
